name: Run Testes

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        id: test-run
        run: npm test
        continue-on-error: true

      - name: Publicar relatório HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: reports/

      - name: Validar resultado dos testes
        if: steps.test-run.outcome == 'failure'
        run: exit 1
